// BreakoutPro - CandleDetailData.jsx
// Educational detail for each candlestick pattern. No advice. Rules: no backtick, no triple-equals, ASCII.

function mk(psy,form,where,rel,conf,tf,mist,edu){
  return {psychology:psy,formation:form,where:where,reliability:rel,confirmation:conf,timeframe:tf,mistakes:mist,edu:edu};
}
var D="Educational observation only. This explains how the pattern forms and what it may indicate; it is not a prediction or advice.";

export var CANDLE_DETAIL={
  "Bullish Engulfing":mk("Buyers overwhelm sellers after a decline, shifting control upward.","A small bearish candle is followed by a larger bullish candle that fully covers the prior body.","At the end of a downtrend or near support.","High","Wait for the next candle to hold above the engulfing close.","1H and Daily are more reliable than 1m.","Acting before the candle closes; ignoring the prior trend.",D),
  "Bearish Engulfing":mk("Sellers overwhelm buyers after a rise, shifting control downward.","A small bullish candle is followed by a larger bearish candle that fully covers the prior body.","At the end of an uptrend or near resistance.","High","Wait for the next candle to stay below the engulfing close.","1H and Daily preferred.","Trading it mid-range without a prior trend.",D),
  "Doji":mk("Buyers and sellers reach balance; indecision appears.","Open and close are almost equal, leaving a very small body with wicks.","After an extended move, signalling possible pause or reversal.","Medium","Needs a confirming candle in the expected direction.","Higher timeframes filter noise.","Treating every doji as a reversal; many are just pauses.",D),
  "Long Legged Doji":mk("Strong indecision with wide swings but no net movement.","Long upper and lower wicks with a tiny central body.","After a strong trend, showing exhaustion.","Low","Strong confirmation required.","Daily and above.","Reading it in isolation on low timeframes.",D),
  "Dragonfly Doji":mk("Sellers pushed price down but buyers reclaimed the losses.","Long lower wick with open, close and high near the same level.","At support after a decline.","Medium","Confirm with a bullish follow-through candle.","1H and Daily.","Confusing it with a hammer without context.",D),
  "Gravestone Doji":mk("Buyers pushed up but sellers reclaimed all gains.","Long upper wick with open, close and low near the same level.","At resistance after a rise.","Medium","Confirm with a bearish follow-through candle.","1H and Daily.","Ignoring the prior uptrend.",D),
  "Hammer":mk("Sellers drove price down but buyers stepped in strongly.","Small body near the top with a long lower wick.","After a downtrend, near support.","High","A bullish candle after the hammer strengthens it.","1H and Daily.","Buying without confirmation; ignoring trend context.",D),
  "Hanging Man":mk("Selling appeared during an uptrend even though price recovered.","Small body near the top with a long lower wick, after a rise.","At the top of an uptrend.","Medium","Needs a bearish confirmation candle.","1H and Daily.","Confusing it with a hammer; they look alike but appear in opposite trends.",D),
  "Inverted Hammer":mk("Buyers attempted a push after a decline, hinting at a shift.","Small body near the bottom with a long upper wick.","After a downtrend, near support.","Medium","Confirm with a follow-through bullish candle.","1H and Daily.","Entering early without confirmation.",D),
  "Shooting Star":mk("Buyers pushed up but sellers rejected the highs.","Small body near the bottom with a long upper wick, after a rise.","At the top of an uptrend.","High","Confirm with a bearish candle next.","1H and Daily.","Confusing with inverted hammer; check the trend.",D),
  "Morning Star":mk("Selling fades, indecision forms, then buyers take over.","Three candles: a bearish candle, a small-bodied candle, then a strong bullish candle.","At the bottom of a downtrend.","High","The third candle should close well into the first candle body.","Daily is classic.","Skipping the middle candle context.",D),
  "Evening Star":mk("Buying fades, indecision forms, then sellers take over.","Three candles: a bullish candle, a small-bodied candle, then a strong bearish candle.","At the top of an uptrend.","High","The third candle should close well into the first candle body.","Daily is classic.","Ignoring the small middle candle.",D),
  "Three White Soldiers":mk("Steady, consistent buying over three sessions.","Three long bullish candles, each opening within and closing above the prior.","After a downtrend or consolidation.","High","Watch for over-extension after the third candle.","Daily.","Chasing after the move is already extended.",D),
  "Three Black Crows":mk("Steady, consistent selling over three sessions.","Three long bearish candles, each opening within and closing below the prior.","After an uptrend or consolidation.","High","Watch for over-extension after the third candle.","Daily.","Entering late after a long drop.",D),
  "Harami":mk("Momentum slows as the second candle stays inside the first.","A large candle followed by a small candle within its body.","After a strong trend.","Medium","Needs confirmation in the reversal direction.","1H and Daily.","Treating it as a strong signal by itself.",D),
  "Harami Cross":mk("Momentum stalls sharply as a doji forms inside the prior body.","A large candle followed by a doji within its range.","After a strong trend.","Medium","Confirm with a follow-through candle.","1H and Daily.","Ignoring the location within the trend.",D),
  "Piercing Line":mk("Buyers reclaim more than half of the prior decline.","A bearish candle followed by a bullish candle closing above its midpoint.","At the bottom of a downtrend.","Medium","Confirm with continued strength.","1H and Daily.","Confusing with bullish engulfing.",D),
  "Dark Cloud Cover":mk("Sellers reclaim more than half of the prior advance.","A bullish candle followed by a bearish candle closing below its midpoint.","At the top of an uptrend.","Medium","Confirm with continued weakness.","1H and Daily.","Confusing with bearish engulfing.",D),
  "Marubozu":mk("One side controls the entire session with no hesitation.","A full-body candle with little or no wick.","In trends or at breakouts.","Medium","Read with volume and trend context.","Any timeframe with volume.","Assuming continuation without context.",D),
  "Bullish Marubozu":mk("Buyers control the whole session with no wicks.","A full green body with no meaningful wick.","During strength or breakouts.","Medium","Confirm with volume.","Any timeframe.","Chasing without context.",D),
  "Bearish Marubozu":mk("Sellers control the whole session with no wicks.","A full red body with no meaningful wick.","During weakness or breakdowns.","Medium","Confirm with volume.","Any timeframe.","Chasing without context.",D),
  "Spinning Top":mk("Both sides fight but neither wins; indecision.","Small body with upper and lower wicks of similar length.","After a move, signalling a pause.","Low","Strong confirmation needed.","Higher timeframes.","Over-interpreting a common candle.",D),
  "Tweezer Top":mk("Buyers fail twice at the same high.","Two candles with matching or near-matching highs.","At resistance after a rise.","Medium","Confirm with a bearish candle.","1H and Daily.","Requiring exact highs; near matches count.",D),
  "Tweezer Bottom":mk("Sellers fail twice at the same low.","Two candles with matching or near-matching lows.","At support after a decline.","Medium","Confirm with a bullish candle.","1H and Daily.","Requiring exact lows; near matches count.",D),
  "Inside Bar":mk("Volatility contracts as range narrows inside the prior bar.","A candle whose range sits fully inside the prior candle.","During consolidation or before breakouts.","Low","Wait for a break of the prior bar range.","Any timeframe.","Trading inside the bar instead of the breakout.",D),
  "Outside Bar":mk("Volatility expands as the candle engulfs the prior range.","A candle whose range fully covers the prior candle high and low.","At turning points or breakouts.","Medium","Confirm the direction of the close.","Any timeframe.","Ignoring where the candle closes.",D),
  "Rising Three Methods":mk("A brief pause during an uptrend that then resumes.","A long bullish candle, a few small pause candles, then another bullish candle.","Within an established uptrend.","Medium","The final candle should break above the first candle high.","Daily.","Mistaking the pause for a reversal.",D),
  "Falling Three Methods":mk("A brief pause during a downtrend that then resumes.","A long bearish candle, a few small pause candles, then another bearish candle.","Within an established downtrend.","Medium","The final candle should break below the first candle low.","Daily.","Mistaking the pause for a bottom.",D)
};
