var UP="#22C55E",DOWN="#EF4444",BLUE="#3B82F6";

// Each category: id, title, icon, items[] -> {label, value, sub, up(optional)}
var CATEGORIES=[
  {id:"market",title:"Market Overview",icon:"&#127968;",items:[
    {label:"NIFTY 50",value:"23,969.20",sub:"+1.47%",up:true},
    {label:"SENSEX",value:"76,692.70",sub:"+1.54%",up:true},
    {label:"BANK NIFTY",value:"52,134.80",sub:"+1.69%",up:true},
    {label:"FINNIFTY",value:"23,410.50",sub:"+0.92%",up:true},
    {label:"MIDCAP 50",value:"43,876.20",sub:"+0.74%",up:true},
    {label:"SMALLCAP",value:"15,234.10",sub:"-0.31%",up:false},
    {label:"INDIA VIX",value:"13.42",sub:"-2.10%",up:false},
    {label:"GIFT NIFTY",value:"24,012.50",sub:"+0.32%",up:true},
  ]},
  {id:"sentiment",title:"Market Sentiment",icon:"&#128522;",items:[
    {label:"Market Mood",value:"Bullish",sub:"72% confidence",up:true},
    {label:"Fear & Greed",value:"Greed",sub:"Index: 68",up:true},
    {label:"Advance/Decline",value:"1.8:1",sub:"Advances leading",up:true},
    {label:"Market Breadth",value:"Positive",sub:"1240 adv / 690 dec",up:true},
    {label:"Bullish %",value:"64%",sub:"vs 36% bearish",up:true},
  ]},
  {id:"fiidii",title:"FII / DII Data",icon:"&#127974;",items:[
    {label:"FII Cash",value:"+2,840 Cr",sub:"Net Buy",up:true},
    {label:"DII Cash",value:"+1,120 Cr",sub:"Net Buy",up:true},
    {label:"Net Flow",value:"+3,960 Cr",sub:"Total inflow",up:true},
    {label:"FII Long/Short",value:"1.65",sub:"Index futures ratio",up:true},
  ]},
  {id:"movers",title:"Market Movers",icon:"&#128200;",items:[
    {label:"Top Gainers",value:"View 10",sub:"Best performers",link:"markets"},
    {label:"Top Losers",value:"View 10",sub:"Worst performers",link:"markets"},
    {label:"Most Active",value:"View 10",sub:"By trade count",link:"markets"},
    {label:"Volume Leaders",value:"View 10",sub:"By volume",link:"markets"},
    {label:"Delivery Leaders",value:"View 10",sub:"By delivery %",link:"markets"},
    {label:"52W High",value:"View 12",sub:"New highs today",link:"markets"},
    {label:"52W Low",value:"View 4",sub:"New lows today",link:"markets"},
    {label:"Upper Circuit",value:"View 6",sub:"Locked upper",link:"markets"},
    {label:"Lower Circuit",value:"View 2",sub:"Locked lower",link:"markets"},
  ]},
  {id:"breakout",title:"Breakout Data",icon:"&#128293;",items:[
    {label:"Breakout Stocks",value:"View 8",sub:"Resistance crossed",link:"scan"},
    {label:"Breakdown Stocks",value:"View 5",sub:"Support broken",link:"scan"},
    {label:"Gap Up",value:"View 14",sub:"Opened higher",link:"scan"},
    {label:"Gap Down",value:"View 9",sub:"Opened lower",link:"scan"},
    {label:"Volume Spike",value:"View 11",sub:"Unusual activity",link:"scan"},
    {label:"Price Spike",value:"View 6",sub:"Sharp moves",link:"scan"},
    {label:"Unusual Volume",value:"View 7",sub:"Above average",link:"scan"},
  ]},
  {id:"technical",title:"Technical Signals",icon:"&#128202;",items:[
    {label:"EMA Crossover",value:"View 9",sub:"9/21 cross",link:"scan"},
    {label:"RSI Oversold",value:"View 5",sub:"RSI < 30",link:"scan"},
    {label:"RSI Overbought",value:"View 7",sub:"RSI > 70",link:"scan"},
    {label:"MACD Bullish",value:"View 12",sub:"Signal cross up",link:"scan"},
    {label:"MACD Bearish",value:"View 6",sub:"Signal cross down",link:"scan"},
    {label:"Supertrend",value:"View 10",sub:"Trend flip",link:"scan"},
    {label:"VWAP Cross",value:"View 8",sub:"Price vs VWAP",link:"scan"},
    {label:"ORB",value:"View 4",sub:"Opening range break",link:"scan"},
  ]},
  {id:"options",title:"Options Data",icon:"&#127974;",items:[
    {label:"PCR",value:"1.12",sub:"Put-Call Ratio",up:true},
    {label:"Max Pain",value:"23,900",sub:"NIFTY weekly",up:null},
    {label:"OI Change",value:"+8.4L",sub:"Net change",up:true},
    {label:"Call OI",value:"42.1L",sub:"Total calls",up:null},
    {label:"Put OI",value:"47.2L",sub:"Total puts",up:null},
    {label:"IV",value:"14.8%",sub:"Avg implied vol",up:null},
    {label:"Long Buildup",value:"View 6",sub:"Price+OI up",link:"oi"},
    {label:"Short Buildup",value:"View 4",sub:"Price down,OI up",link:"oi"},
    {label:"Short Covering",value:"View 5",sub:"Price up,OI down",link:"oi"},
    {label:"Long Unwinding",value:"View 3",sub:"Price+OI down",link:"oi"},
  ]},
  {id:"global",title:"Global Markets",icon:"&#127757;",items:[
    {label:"Dow Jones",value:"42,750",sub:"+234 pts",up:true},
    {label:"Nasdaq",value:"18,920",sub:"+87 pts",up:true},
    {label:"S&P 500",value:"5,892",sub:"+0.6%",up:true},
    {label:"Nikkei",value:"38,540",sub:"-0.3%",up:false},
    {label:"Hang Seng",value:"18,230",sub:"+0.9%",up:true},
    {label:"FTSE",value:"8,210",sub:"+0.2%",up:true},
    {label:"DAX",value:"18,640",sub:"+0.4%",up:true},
    {label:"Dollar Index",value:"104.2",sub:"-0.1%",up:false},
  ]},
  {id:"commodities",title:"Commodities",icon:"&#129747;",items:[
    {label:"Gold",value:"71,245",sub:"+0.45%",up:true},
    {label:"Silver",value:"87,654",sub:"+0.82%",up:true},
    {label:"Crude Oil",value:"6,823",sub:"-0.34%",up:false},
    {label:"Natural Gas",value:"243",sub:"+1.20%",up:true},
    {label:"Copper",value:"812",sub:"+0.55%",up:true},
    {label:"Aluminium",value:"224",sub:"-0.18%",up:false},
  ]},
  {id:"currency",title:"Currency",icon:"&#128176;",items:[
    {label:"USD/INR",value:"83.42",sub:"-0.05%",up:false},
    {label:"EUR/INR",value:"90.18",sub:"+0.12%",up:true},
    {label:"GBP/INR",value:"105.64",sub:"+0.08%",up:true},
    {label:"JPY/INR",value:"0.535",sub:"-0.03%",up:false},
  ]},
  {id:"news",title:"News Data",icon:"&#128240;",items:[
    {label:"Breaking News",value:"View Live",sub:"Latest updates",link:"news"},
    {label:"Positive News",value:"View 8",sub:"Bullish news",link:"news"},
    {label:"Negative News",value:"View 3",sub:"Bearish news",link:"news"},
    {label:"Sector News",value:"View 12",sub:"By sector",link:"news"},
    {label:"Earnings News",value:"View 6",sub:"Q4 results",link:"news"},
    {label:"AI News Summary",value:"View",sub:"AI digest",link:"news"},
  ]},
  {id:"sector",title:"Sector Data",icon:"&#127981;",items:[
    {label:"IT",value:"+1.2%",sub:"Outperforming",up:true},
    {label:"Banking",value:"+0.8%",sub:"Steady",up:true},
    {label:"Pharma",value:"-0.4%",sub:"Weak",up:false},
    {label:"Auto",value:"+0.3%",sub:"Mild gain",up:true},
    {label:"FMCG",value:"-0.2%",sub:"Flat",up:false},
    {label:"Metal",value:"+1.5%",sub:"Strong",up:true},
    {label:"Realty",value:"+0.6%",sub:"Positive",up:true},
    {label:"Energy",value:"-0.1%",sub:"Flat",up:false},
  ]},
  {id:"institutional",title:"Institutional Data",icon:"&#128221;",items:[
    {label:"Bulk Deals",value:"View 9",sub:"Today's deals",link:"news"},
    {label:"Block Deals",value:"View 4",sub:"Large trades",link:"news"},
    {label:"Insider Trading",value:"View 6",sub:"Recent filings",link:"news"},
    {label:"Shareholding",value:"View",sub:"Pattern changes",link:"news"},
    {label:"Pledge Data",value:"View 3",sub:"Promoter pledges",link:"news"},
  ]},
  {id:"events",title:"Events",icon:"&#128197;",items:[
    {label:"Earnings Calendar",value:"View 14",sub:"This week",link:"more"},
    {label:"IPO Calendar",value:"View 2",sub:"Upcoming IPOs",link:"more"},
    {label:"Dividend Calendar",value:"View 8",sub:"Ex-dates",link:"more"},
    {label:"Bonus Issues",value:"View 1",sub:"Announced",link:"more"},
    {label:"Stock Split",value:"View 2",sub:"Announced",link:"more"},
    {label:"AGM Dates",value:"View 5",sub:"This month",link:"more"},
  ]},
  {id:"alerts",title:"Smart Alerts",icon:"&#128276;",items:[
    {label:"Price Alerts",value:"Manage",sub:"Set custom levels",link:"alerts"},
    {label:"Breakout Alerts",value:"Manage",sub:"Auto-detect",link:"alerts"},
    {label:"Volume Alerts",value:"Manage",sub:"Spike detection",link:"alerts"},
    {label:"OI Alerts",value:"Manage",sub:"Options buildup",link:"alerts"},
    {label:"News Alerts",value:"Manage",sub:"Breaking news",link:"alerts"},
  ]},
];

export { CATEGORIES };
