// BreakoutPro - FuturesData.jsx
// Educational detail content for Futures + Gamma metrics. Rules: no backtick, no triple-equals, ASCII.

// detail content for each futures metric + gamma metric
export var FUT_DETAIL={
  "Long Build-up":{what:"Long build-up means price is rising while Open Interest is also rising. New buyers are adding fresh long positions.",why:"It happens when participants expect strength and add new long contracts, pushing both price and OI up together.",watch:"Traders watch it as a sign of bullish participation and conviction in the current move.",obs:"Rising price with rising OI observed on the current futures contract.",hist:"Historically, sustained long build-up has accompanied trending up-moves, though it can reverse near resistance.",ai:"Long build-up is increasing with rising Open Interest and price. Educationally this indicates bullish futures participation. Observation only."},
  "Short Build-up":{what:"Short build-up means price is falling while Open Interest is rising. New sellers are adding fresh short positions.",why:"It happens when participants expect weakness and add short contracts, pushing price down as OI rises.",watch:"Traders watch it as a sign of bearish participation and selling pressure.",obs:"Falling price with rising OI observed on the current contract.",hist:"Historically, short build-up has accompanied down-trends and can intensify near breakdowns.",ai:"Short build-up shows falling price with rising OI. Educationally this indicates bearish participation. Observation only."},
  "Long Unwinding":{what:"Long unwinding means price is falling and Open Interest is also falling. Existing longs are closing positions.",why:"It happens when long holders book profits or exit, reducing OI as price eases.",watch:"Traders watch it to gauge weakening bullish conviction.",obs:"Falling price with falling OI observed.",hist:"Historically, long unwinding often marks pauses or the end of an up-move.",ai:"Long unwinding shows longs exiting as price and OI fall. Educationally this signals fading bullish interest. Observation only."},
  "Short Covering":{what:"Short covering means price is rising while Open Interest is falling. Existing shorts are buying back positions.",why:"It happens when short holders exit to limit losses or book profit, lifting price as OI drops.",watch:"Traders watch it as it can cause sharp upward moves.",obs:"Rising price with falling OI observed.",hist:"Historically, short covering has driven fast relief rallies.",ai:"Short covering shows shorts exiting as price rises and OI falls. Educationally this can lift price temporarily. Observation only."},
  "OI Change":{what:"Open Interest change is the shift in total outstanding futures contracts over a period.",why:"OI rises when new positions open and falls when positions close, reflecting participation.",watch:"Traders watch OI with price to classify build-up or unwinding.",obs:"Open interest change observed on the current contract.",hist:"Historically, large OI shifts precede volatility expansions.",ai:"OI change combined with price direction helps classify market structure. Observation only."},
  "Price Change":{what:"Price change is the movement of the futures contract price versus a prior reference.",why:"It reflects net buying or selling pressure during the session.",watch:"Traders watch price with OI and volume for context.",obs:"Futures price movement observed for the session.",hist:"Historically, price with confirming volume tends to sustain longer.",ai:"Price change alone is neutral until read with OI and volume. Observation only."},
  "Volume":{what:"Volume is the number of futures contracts traded in a period.",why:"High volume shows active participation, low volume shows caution.",watch:"Traders watch volume to confirm the strength of a move.",obs:"Traded contract volume observed as elevated.",hist:"Historically, moves on high volume are considered more reliable than low-volume moves.",ai:"Elevated volume suggests active participation in the current move. Observation only."},
  "Basis":{what:"Basis is the difference between the futures price and the underlying spot price.",why:"It reflects cost of carry, interest rates and demand for futures.",watch:"Traders watch basis to understand premium or discount conditions.",obs:"Positive basis observed, futures above spot.",hist:"Historically, basis narrows toward expiry as futures converge with spot.",ai:"A positive basis shows futures trading above spot. Educationally this is a premium condition. Observation only."},
  "Cost of Carry":{what:"Cost of carry is the annualised cost of holding a futures position, tied to interest and time to expiry.",why:"It arises from financing costs and time value embedded in futures pricing.",watch:"Traders watch it to compare futures pricing fairness.",obs:"Cost of carry observed at a moderate annualised level.",hist:"Historically, cost of carry declines as expiry approaches.",ai:"Cost of carry reflects the financing embedded in the futures price. Observation only."},
  "Premium / Discount":{what:"Premium means futures trade above spot, discount means below spot.",why:"It reflects sentiment, carry and demand for leverage.",watch:"Traders watch it to gauge positioning bias.",obs:"Futures observed at a premium to spot.",hist:"Historically, deep premium can signal bullish positioning and deep discount bearish.",ai:"A premium condition shows futures above spot. Educationally this reflects carry and sentiment. Observation only."}
};
export var GAMMA_DETAIL={
  "Gamma Blast Probability":{what:"Gamma Blast Probability is an educational estimate of a sharp expiry-driven move as dealers hedge gamma.",why:"Near expiry, concentrated gamma plus hedging flows can accelerate moves.",watch:"Traders watch it to understand expiry volatility risk.",obs:"Moderate gamma blast conditions observed near current strike.",hist:"Historically, gamma blasts occur on expiry days near heavy OI strikes.",ai:"Moderate gamma blast probability observed. Educationally, expiry hedging can accelerate moves. Very high risk. Observation only."},
  "Gamma Exposure":{what:"Gamma Exposure (GEX) estimates dealer hedging sensitivity to price moves.",why:"Positive GEX tends to dampen volatility, negative GEX can amplify it.",watch:"Traders watch it to gauge whether dealers stabilise or accelerate moves.",obs:"Positive gamma exposure observed near current strike.",hist:"Historically, positive GEX zones see range-bound behaviour.",ai:"Positive gamma exposure observed. Educationally this may reduce volatility until levels are crossed. Observation only."},
  "Gamma Flip":{what:"Gamma Flip is the price level where dealer gamma flips from positive to negative.",why:"Above the flip, dealers dampen moves; below it, they can amplify them.",watch:"Traders watch the flip as a volatility regime boundary.",obs:"Gamma flip level observed below the current spot.",hist:"Historically, crossing the flip has coincided with volatility changes.",ai:"Gamma flip level observed nearby. Educationally, crossing it can change volatility behaviour. Observation only."},
  "Max Pain":{what:"Max Pain is the strike where the most option buyers would lose value at expiry.",why:"It reflects where open interest is concentrated across calls and puts.",watch:"Traders watch it as a magnet level into expiry.",obs:"Max pain observed near the current spot.",hist:"Historically, price sometimes gravitates toward max pain at expiry.",ai:"Max pain observed near spot. Educationally this is an OI-weighted reference, not a prediction. Observation only."},
  "Call Wall":{what:"Call Wall is the strike with the largest call Open Interest, often acting as resistance.",why:"Heavy call OI can create hedging that slows upward moves.",watch:"Traders watch it as a potential resistance zone.",obs:"Call wall observed above current spot.",hist:"Historically, price often stalls near heavy call walls.",ai:"Call wall observed above spot. Educationally this can act as observed resistance. Observation only."},
  "Put Wall":{what:"Put Wall is the strike with the largest put Open Interest, often acting as support.",why:"Heavy put OI can create hedging that cushions downward moves.",watch:"Traders watch it as a potential support zone.",obs:"Put wall observed below current spot.",hist:"Historically, price often finds support near heavy put walls.",ai:"Put wall observed below spot. Educationally this can act as observed support. Observation only."}
};

// tiny deterministic series for detail charts (candles + volume + oi)
export function detailSeries(key){
  var seed=0; for(var i=0;i<key.length;i++){ seed+=key.charCodeAt(i); }
  var base=100+(seed%40), candles=[], vol=[], oi=[];
  var p=base;
  for(var j=0;j<20;j++){
    var o=p, mv=((seed*(j+3))%7)-3, c=o+mv;
    var hi=Math.max(o,c)+((seed+j)%3), lo=Math.min(o,c)-((seed+j*2)%3);
    candles.push({o:o,c:c,h:hi,l:lo,up:c>=o});
    vol.push(20+((seed*(j+1))%80));
    oi.push(base*10+((seed*(j+2))%120));
    p=c;
  }
  return {candles:candles,vol:vol,oi:oi};
}
