// BreakoutPro - OptSellHubData.jsx
// Detail content for every clickable card in the Option Sellers Daily Hub.
// Educational only. Terminology English. Rules: no backtick, no triple-equals, ASCII.

export function getHubDetail(id){ return DETAILS[id]||DETAILS.possize; }

// each: title, icon, explanation, why, examples[], ai, mistakes[], best[], quiz[], related[]
var DETAILS = {
  // RISK
  possize:{ title:"Position Sizing", icon:"&#128207;",
    explanation:"Position sizing decides how much capital to commit to a single position so that one loss cannot seriously damage your account. For option sellers, where losses can be large, it is the single most important risk control.",
    why:"Sellers face undefined risk in some strategies. Without sizing, one bad expiry can wipe out months of premium income.",
    examples:["If capital is 5 lakh and you risk 2% per idea, the most you let a single position cost you is about 10,000.","A seller who deploys full margin on one short straddle can face a margin call on a single gap."],
    ai:"Sizing by a fixed percentage of capital keeps every position survivable. Many professional sellers risk only 1-2% per idea and never let one expiry decide their year.",
    mistakes:["Using full available margin on one position","Adding to a losing position to average","Sizing by greed, not by risk"],
    best:["Risk a fixed small percent per idea","Keep spare margin for adjustments","Scale size to volatility"],
    quiz:[{q:"Why is position sizing vital for option sellers?",opts:["To maximise leverage","To survive large or undefined losses","To avoid taxes","To beat the index"],a:1}],
    related:["Margin Awareness","Volatility Risk"] },
  margin:{ title:"Margin Awareness", icon:"&#128176;",
    explanation:"Margin is the capital blocked by the broker to cover potential losses on short options. It changes with volatility and can rise suddenly, forcing you to add funds or close positions.",
    why:"A margin spike during a volatile day can trigger a margin call at the worst possible time, forcing exits at bad prices.",
    examples:["Short straddle margin can jump when India VIX spikes, even if price has not moved much.","Span plus exposure margin can rise into events like budget or results."],
    ai:"Margin is not fixed. Sellers study span and exposure margin and keep a buffer so a volatility spike does not force a panic exit.",
    mistakes:["Using all margin with no buffer","Ignoring margin rises before events","Not knowing span vs exposure margin"],
    best:["Keep a margin buffer of 30 to 50 percent","Check margin before events","Reduce size when VIX is high"],
    quiz:[{q:"What can cause margin to rise suddenly?",opts:["Lower volatility","A volatility spike","More cash in account","Holiday"],a:1}],
    related:["Position Sizing","Volatility Risk"] },
  eventrisk:{ title:"Event Risk", icon:"&#128197;",
    explanation:"Event risk is the danger of sharp moves around scheduled events such as RBI policy, the Union Budget, company results, Fed decisions, and expiry. Options can move violently and IV can swing hard around these.",
    why:"Sellers collect small premium but can face large moves on events, a poor risk-reward if unprepared.",
    examples:["RBI policy day can move Bank Nifty sharply in minutes.","Union Budget day often sees wide intraday swings.","A company result can gap the stock well beyond the expected move.","Fed decisions move global risk and India opens with gaps."],
    ai:"Sellers study the event calendar and often reduce size or avoid naked positions into major events, because IV crush after the event can help but the move itself can hurt.",
    mistakes:["Selling naked into results","Ignoring the global event calendar","Underestimating budget-day swings"],
    best:["Mark RBI, Budget, Fed, and result dates","Reduce size into events","Prefer defined-risk structures around events"],
    quiz:[{q:"Which is an event risk for option sellers?",opts:["A calm Tuesday","RBI policy day","Lunch break","A normal expiry-free week"],a:1}],
    related:["Gap Risk","Volatility Risk"] },
  gaprisk:{ title:"Gap Risk", icon:"&#9889;",
    explanation:"Gap risk is when price opens far from the previous close due to overnight news, leaving no chance to react. For sellers, a gap can push price past short strikes instantly.",
    why:"Stop levels do not help across a gap. The market simply opens beyond them, and short positions can show large losses at the open.",
    examples:["A global selloff overnight can gap Nifty down hundreds of points at open.","Stock-specific news can gap a stock past a short call strike before you can act."],
    ai:"Because gaps skip over levels, sellers study overnight risk and often use defined-risk spreads so the maximum loss is known even on a violent gap.",
    mistakes:["Holding naked shorts through risky news","Assuming a stop will protect across a gap","Ignoring global cues overnight"],
    best:["Prefer defined-risk over naked when holding overnight","Watch global markets and news","Size for a possible gap"],
    quiz:[{q:"Why is a stop level weak against gap risk?",opts:["Stops always fill exactly","Price can open beyond the stop","Gaps never happen","Brokers prevent gaps"],a:1}],
    related:["Event Risk","Position Sizing"] },
  volrisk:{ title:"Volatility Risk", icon:"&#128200;",
    explanation:"Volatility risk covers how changes in implied volatility affect option prices. A sudden IV spike raises premiums and hurts short positions, while an IV crush after events lowers them and can help sellers.",
    why:"Sellers are short Vega, so rising IV works against them even if price does not move. Understanding VIX and IV is essential.",
    examples:["India VIX jumping from 12 to 18 can inflate option prices and short-position losses.","After a major result, IV crush can collapse premiums, helping sellers who survived the move."],
    ai:"Sellers study IV Rank and VIX to judge whether premium is rich or cheap, and they respect that a calm market can turn volatile quickly.",
    mistakes:["Selling when IV is already very low","Ignoring a rising VIX","Confusing realised and implied volatility"],
    best:["Prefer selling when IV is elevated","Watch VIX and IV Rank","Reduce size as volatility rises"],
    quiz:[{q:"Sellers are generally short which Greek related to volatility?",opts:["Delta","Vega","Rho","None"],a:1}],
    related:["Margin Awareness","Event Risk"] },
  emotion:{ title:"Emotional Discipline", icon:"&#129504;",
    explanation:"Emotional discipline is the ability to follow your plan calmly, especially under stress. Fear and greed cause most trading mistakes, and option selling tests patience because most days are quiet until they are not.",
    why:"A single panic adjustment can turn a small managed loss into a large one. Discipline protects the edge that analysis provides.",
    examples:["A seller who panics on a small adverse move may close at the worst point, just before mean reversion.","Overconfidence after a winning streak often leads to oversizing the next position."],
    ai:"A written plan, journaling, and accepting losses as part of the process build the steadiness that option selling demands.",
    mistakes:["Revenge trading after a loss","Oversizing after a win","Abandoning the plan under stress"],
    best:["Keep a written plan and follow it","Journal every decision","Accept losses as a cost of doing business"],
    quiz:[{q:"What most often causes trading mistakes?",opts:["Too much analysis","Fear and greed","Slow internet","Reading news"],a:1}],
    related:["Position Sizing","Event Risk"] },
  // EXPIRY topics
  weekly:{ title:"Weekly Expiry", icon:"&#128197;",
    explanation:"Weekly index options expire every Thursday. They have little time value, so Theta decay is fast and Gamma risk is high, especially on expiry day.",
    why:"Most retail option activity is in weeklies, so understanding their fast decay and sharp expiry-day moves is essential.",
    examples:["On expiry afternoon, an at-the-money option can lose most of its value in hours.","A small late move can swing a near-strike option sharply due to high Gamma."],
    ai:"Weeklies reward sellers with fast Theta but punish them with high Gamma near the close. Sellers study how quickly risk changes on Thursday.",
    mistakes:["Holding near-strike shorts into the last hour without a plan","Underestimating expiry-day Gamma"],
    best:["Respect Gamma near expiry","Have a clear expiry-day plan","Size down on expiry day"],
    quiz:[{q:"What is highest near weekly expiry?",opts:["Time value","Gamma risk","Liquidity gaps only","Dividends"],a:1}],
    related:["Gamma Risk","Time Decay Behaviour"] },
  monthly:{ title:"Monthly Expiry", icon:"&#128198;",
    explanation:"Monthly options expire on the last Thursday of the month. They carry more time value and behave more smoothly than weeklies far from expiry.",
    why:"Monthly contracts suit position trades and hedges, with slower decay early and faster decay near the end.",
    examples:["A monthly option a few weeks out moves more with IV than with daily Theta.","In the final week, a monthly behaves much like a weekly with fast decay."],
    ai:"Monthlies give sellers more premium and a slower start, but the same expiry-week risks appear in the final days.",
    mistakes:["Treating a near-expiry monthly as still calm","Ignoring IV impact early in the cycle"],
    best:["Use monthlies for slower positions","Watch the final week closely","Mind IV early in the cycle"],
    quiz:[{q:"When does a monthly option decay fastest?",opts:["First day","Final week","Never","Mid-month only"],a:1}],
    related:["Weekly Expiry","Time Decay Behaviour"] },
  timedecay:{ title:"Time Decay Behaviour", icon:"&#9201;",
    explanation:"Time decay, measured by Theta, is the daily loss of option value as expiry approaches. It is slow far from expiry and accelerates sharply in the final days.",
    why:"Time decay is the seller's main edge. Knowing its shape helps sellers understand when premium erodes fastest.",
    examples:["The last two days before expiry see the steepest premium erosion.","An at-the-money weekly loses value quickly each afternoon near expiry."],
    ai:"Theta is non-linear. Sellers study the steep end-of-cycle decay while respecting that Gamma risk rises at the same time.",
    mistakes:["Expecting steady daily decay","Ignoring that Gamma rises as Theta does"],
    best:["Understand the decay curve","Balance Theta gain against Gamma risk"],
    quiz:[{q:"When does Theta decay accelerate?",opts:["Far from expiry","Near expiry","Never","Only monthly"],a:1}],
    related:["Gamma Risk","Weekly Expiry"] },
  gammarisk:{ title:"Gamma Risk", icon:"&#9889;",
    explanation:"Gamma risk is the danger that Delta changes very fast near expiry. A small price move can flip a position from safe to deeply in the money in minutes.",
    why:"High Gamma near expiry means a calm short position can suddenly carry large directional risk.",
    examples:["On expiry day, a near-strike short option can swing from worthless to costly on a small move.","Dealers hedging high Gamma can amplify the move further."],
    ai:"Gamma is highest at-the-money near expiry. Sellers study it because it is the source of sudden expiry-day losses.",
    mistakes:["Holding near-strike shorts into expiry casually","Underestimating how fast Delta shifts"],
    best:["Reduce near-strike exposure into expiry","Watch Gamma as expiry nears"],
    quiz:[{q:"Gamma risk is highest when?",opts:["Far from expiry, far OTM","At-the-money near expiry","On holidays","After expiry"],a:1}],
    related:["Time Decay Behaviour","Weekly Expiry"] },
  volchange:{ title:"Volatility Changes", icon:"&#128201;",
    explanation:"Implied volatility rises and falls with fear and events. IV often falls into calm expiries and spikes around shocks, changing option premiums sharply.",
    why:"Because sellers are short Vega, IV changes affect their positions even when price is steady.",
    examples:["IV often drops on a quiet week, helping sellers.","A surprise event can spike IV and inflate short-position losses."],
    ai:"Sellers track IV Rank and VIX to judge whether selling premium is attractive, and they prepare for sudden IV expansion.",
    mistakes:["Ignoring IV when selling","Selling into already low IV"],
    best:["Sell when IV is relatively high","Watch VIX for regime shifts"],
    quiz:[{q:"What happens to premiums when IV spikes?",opts:["They fall","They rise","No change","They vanish"],a:1}],
    related:["Volatility Risk","Event Risk"] },
  sellerconsider:{ title:"Seller Considerations", icon:"&#128270;",
    explanation:"Before expiry, option sellers commonly study margin, the distance of their strikes from spot, the event calendar, and their adjustment plan.",
    why:"Preparation reduces panic. Knowing your plan before expiry week helps you act calmly if the market moves.",
    examples:["A seller checks if any results or policy events fall in the expiry week.","A seller confirms spare margin in case volatility rises."],
    ai:"Good sellers decide their plan in advance, including when they would adjust or exit, rather than reacting emotionally near expiry.",
    mistakes:["No adjustment plan","Ignoring events in expiry week","No spare margin"],
    best:["Plan adjustments in advance","Keep margin buffer","Check the event calendar"],
    quiz:[{q:"What should sellers check before expiry week?",opts:["Nothing","Events, margin, and strike distance","Only the news anchor","The weather"],a:1}],
    related:["Event Risk","Margin Awareness"] }
};
