// BreakoutPro - OptSellLessonData.jsx
// Lesson content for the Options Selling Academy Learn path. Educational only.
// Terminology English. Rules: no backtick, no triple-equals, ASCII only.

// Ordered lesson list (for next/prev). Each id maps to LESSONS content.
export var LESSON_ORDER = [
  "what-options","calls-puts","premium","intrinsic","timevalue","expiry","strike","chain-basics",
  "what-selling","why-premium","probability","theta","iv-basics","delta","gamma","vega","margin-basics","risk-mgmt",
  "iron-condor","iron-fly","short-strangle","short-straddle","credit-spreads","hedging","greeks-selling","vol-trading","position-adjust","rolling","portfolio-margin","event-trading","expiry-strategies"
];

export function getLesson(id){ return LESSONS[id]||LESSONS["what-options"]; }
export function lessonMeta(id){ var l=LESSONS[id]; return l?{title:l.title,level:l.level}:null; }

function q(question,opts,a){ return {q:question,opts:opts,a:a}; }

var LESSONS = {
  "what-options":{ title:"What are Options?", level:"Beginner", mins:"6 min",
    objectives:["Understand what an option contract is","Know the two types: Call and Put","See how options differ from stocks"],
    explanation:"An option is a contract that gives the buyer the right, but not the obligation, to buy or sell an underlying asset at a fixed price before a set date. The seller takes on the obligation in exchange for a premium.",
    concepts:[{h:"The contract",p:"Each option has an underlying, a strike price, an expiry date, and a premium."},{h:"Right vs obligation",p:"The buyer holds the right; the seller holds the obligation and is paid the premium for it."},{h:"Why they exist",p:"Options let people hedge risk or take a view with defined cost for buyers."}],
    examples:["A Nifty 25000 Call gives the right to benefit if Nifty rises above 25000.","A stock Put gives the right to benefit if the stock falls below the strike."],
    ai:"Options are tools for managing risk and expressing views. For sellers, they are a way to collect premium by taking the other side, accepting obligation in return.",
    formula:"", mistakes:["Thinking options are just cheap stocks","Ignoring expiry"],
    best:["Learn calls and puts first","Always note expiry and strike"],
    quiz:[q("An option gives the buyer the...",["Obligation to trade","Right but not obligation","Guarantee of profit","Ownership of the company"],1),q("Who collects the premium?",["The buyer","The seller","The exchange only","Nobody"],1),q("Every option has all of these EXCEPT?",["Strike price","Expiry","Premium","Guaranteed return"],3)],
    takeaways:["Options = right for buyer, obligation for seller","Defined by strike, expiry, premium"],
    related:["Calls vs Puts","Premium"] },
  "calls-puts":{ title:"Calls vs Puts", level:"Beginner", mins:"6 min",
    objectives:["Tell a Call from a Put","Know who profits when","Understand buyer vs seller views"],
    explanation:"A Call option benefits when price rises above the strike. A Put option benefits when price falls below the strike. Buyers and sellers take opposite sides of each.",
    concepts:[{h:"Call",p:"The right to buy at the strike. Call buyers are bullish; call sellers expect price to stay below the strike."},{h:"Put",p:"The right to sell at the strike. Put buyers are bearish; put sellers expect price to stay above the strike."}],
    examples:["A trader expecting Nifty to stay flat or rise may study selling a Put.","A trader expecting a stock to stay flat or fall may study selling a Call."],
    ai:"Sellers often sell Calls above resistance and Puts below support, collecting premium if price stays in range. This is education, not a recommendation.",
    formula:"Call payoff for buyer = max(0, Price - Strike) - Premium", mistakes:["Confusing call and put direction","Forgetting the seller's opposite view"],
    best:["Map call to up, put to down","Always think buyer and seller sides"],
    quiz:[q("A Call buyer profits when price...",["Falls","Rises above strike","Stays flat only","Never"],1),q("A Put seller expects price to...",["Crash","Stay above the strike","Go to zero","Gap down"],1),q("Who is bearish?",["Call buyer","Put buyer","Put seller","Call seller and put buyer"],1)],
    takeaways:["Call = up, Put = down","Sellers take the opposite side"],
    related:["What are Options?","Strike Price"] },
  "premium":{ title:"Premium", level:"Beginner", mins:"5 min",
    objectives:["Define option premium","Know what drives it","See why sellers receive it"],
    explanation:"Premium is the price of an option, paid by the buyer to the seller. It is made of intrinsic value plus time value and is influenced by volatility, time to expiry, and distance from the strike.",
    concepts:[{h:"Two parts",p:"Premium = intrinsic value + time value."},{h:"What moves it",p:"Higher volatility, more time, and being closer to the money all raise premium."}],
    examples:["A high-IV stock has richer option premiums.","As expiry nears, time value shrinks and premium falls if price is steady."],
    ai:"Sellers are paid premium upfront. The aim is for the option to lose value over time so the seller keeps more of it. Time decay is the seller's friend.",
    formula:"Premium = Intrinsic Value + Time Value", mistakes:["Thinking all premium is profit","Ignoring volatility's effect"],
    best:["Split premium into intrinsic and time","Watch IV before selling"],
    quiz:[q("Premium is made of...",["Only intrinsic value","Intrinsic + time value","Only time value","Brokerage"],1),q("What raises premium?",["Lower volatility","Higher volatility","Less time","Being far OTM"],1),q("Who pays the premium?",["Seller","Buyer","Exchange","Broker"],1)],
    takeaways:["Premium = intrinsic + time value","Driven by IV, time, and strike distance"],
    related:["Intrinsic Value","Time Value"] },
  "intrinsic":{ title:"Intrinsic Value", level:"Beginner", mins:"5 min",
    objectives:["Define intrinsic value","Calculate it for calls and puts","Know in-the-money vs out-of-the-money"],
    explanation:"Intrinsic value is the real, in-the-money portion of an option's price. A Call has intrinsic value when price is above the strike; a Put when price is below the strike.",
    concepts:[{h:"Calls",p:"Intrinsic = Price minus Strike, if positive, else zero."},{h:"Puts",p:"Intrinsic = Strike minus Price, if positive, else zero."}],
    examples:["If Nifty is 25100 and the Call strike is 25000, intrinsic value is 100.","If a stock is 95 and the Put strike is 100, intrinsic value is 5."],
    ai:"Out-of-the-money options have zero intrinsic value and are all time value. Sellers often sell out-of-the-money options so time decay does most of the work.",
    formula:"Call intrinsic = max(0, Price - Strike); Put intrinsic = max(0, Strike - Price)", mistakes:["Counting time value as intrinsic","Forgetting intrinsic cannot be negative"],
    best:["Compute intrinsic first","Then the rest is time value"],
    quiz:[q("A Call is in-the-money when...",["Price below strike","Price above strike","Always","At expiry only"],1),q("Intrinsic value can be...",["Negative","Zero or positive","Any number","Below zero"],1),q("An OTM option's intrinsic value is...",["High","Zero","Negative","Equal to premium"],1)],
    takeaways:["Intrinsic = in-the-money part","Never negative"],
    related:["Premium","Time Value"] },
  "timevalue":{ title:"Time Value", level:"Beginner", mins:"5 min",
    objectives:["Define time value","Understand how it decays","Link it to Theta"],
    explanation:"Time value is the part of premium beyond intrinsic value. It reflects the chance the option gains value before expiry, and it decays to zero by expiry.",
    concepts:[{h:"Decay",p:"Time value shrinks every day, fastest near expiry. This decay is measured by Theta."},{h:"Seller advantage",p:"Sellers benefit as time value erodes, keeping more of the premium."}],
    examples:["A weekly option loses time value quickly in its final two days.","Far-from-expiry options hold more time value."],
    ai:"Time value decay is the engine of option selling. The seller wants the option to expire worthless so all the time value becomes profit.",
    formula:"Time Value = Premium - Intrinsic Value", mistakes:["Expecting steady linear decay","Ignoring expiry timing"],
    best:["Watch the decay curve","Sell when time decay is in your favour"],
    quiz:[q("Time value at expiry is...",["High","Zero","Negative","Maximum"],1),q("Time decay is measured by...",["Delta","Theta","Vega","Rho"],1),q("Time value decays fastest...",["Far from expiry","Near expiry","Never","At open only"],1)],
    takeaways:["Time value decays to zero","Theta measures the decay"],
    related:["Theta Decay","Premium"] },
  "expiry":{ title:"Expiry", level:"Beginner", mins:"5 min",
    objectives:["Understand expiry dates","Know weekly vs monthly","See expiry-day behaviour"],
    explanation:"Expiry is the date an option contract ends. Index options have weekly and monthly expiries. On expiry, options settle at their intrinsic value, and out-of-the-money options expire worthless.",
    concepts:[{h:"Weekly vs monthly",p:"Weeklies expire each Thursday; monthlies on the last Thursday."},{h:"Settlement",p:"At expiry, in-the-money options settle at intrinsic value; OTM options expire worthless."}],
    examples:["A weekly Call expires worthless if price closes below its strike.","Expiry-day moves can be sharp due to high Gamma."],
    ai:"Sellers study expiry closely because Theta is highest and Gamma risk peaks. Expiry day rewards careful planning and punishes carelessness.",
    formula:"", mistakes:["Ignoring Gamma risk on expiry day","Forgetting which expiry you hold"],
    best:["Know your expiry date","Plan for expiry-day volatility"],
    quiz:[q("Index weeklies usually expire on...",["Monday","Thursday","Friday","Month end only"],1),q("An OTM option at expiry...",["Pays intrinsic value","Expires worthless","Always profits","Rolls over"],1),q("Expiry day often has high...",["Dividends","Gamma risk","Liquidity gaps only","Nothing"],1)],
    takeaways:["Weekly and monthly expiries","OTM expires worthless"],
    related:["Strike Price","Time Value"] },
  "strike":{ title:"Strike Price", level:"Beginner", mins:"5 min",
    objectives:["Define strike price","Understand ATM, ITM, OTM","See how strike choice affects risk"],
    explanation:"The strike price is the fixed price at which an option can be exercised. Relative to the current price, options are at-the-money, in-the-money, or out-of-the-money.",
    concepts:[{h:"ATM, ITM, OTM",p:"At-the-money is near the current price; in-the-money has intrinsic value; out-of-the-money does not."},{h:"Strike choice",p:"Strikes closer to price carry more premium and more risk for sellers."}],
    examples:["Selling a far OTM strike collects less premium but has a wider safety buffer.","Selling near ATM collects more premium but carries more risk."],
    ai:"Strike selection is a core seller decision. Closer strikes pay more but risk more; farther strikes pay less with a bigger buffer.",
    formula:"", mistakes:["Selling near strikes for high premium without respecting risk","Ignoring distance from price"],
    best:["Match strike distance to your risk comfort","Understand the premium-risk trade-off"],
    quiz:[q("ATM means strike is...",["Far above price","Near the current price","At zero","At expiry"],1),q("Closer strikes for sellers mean...",["Less premium, less risk","More premium, more risk","No premium","No risk"],1),q("An OTM call strike is...",["Below price","Above price","At price","Irrelevant"],1)],
    takeaways:["Strike sets the exercise price","Distance drives premium and risk"],
    related:["Expiry","Option Chain Basics"] },
  "chain-basics":{ title:"Option Chain Basics", level:"Beginner", mins:"6 min",
    objectives:["Read an option chain","Find OI and IV","Spot key strikes"],
    explanation:"The option chain lists all strikes with their Call and Put data: price, Open Interest, volume, and IV. It is the main screen options traders study.",
    concepts:[{h:"Layout",p:"Calls on one side, Puts on the other, strikes in the middle."},{h:"Key columns",p:"LTP, OI, volume, and IV reveal positioning and activity."}],
    examples:["A strike with very high call OI often acts as resistance (Call Wall).","A strike with very high put OI often acts as support (Put Wall)."],
    ai:"The chain is where PCR, Max Pain, and OI walls come from. Sellers read it to find where the crowd has positioned.",
    formula:"", mistakes:["Looking only at price, ignoring OI","Confusing volume with OI"],
    best:["Scan OI for walls","Note IV across strikes"],
    quiz:[q("High call OI at a strike often acts as...",["Support","Resistance","Nothing","A dividend"],1),q("The chain shows all of these EXCEPT...",["OI","Volume","IV","Your P&L"],3),q("Put Wall is the strike with highest...",["Call OI","Put OI","Volume only","IV only"],1)],
    takeaways:["Chain = all strikes with OI, volume, IV","Source of walls, PCR, Max Pain"],
    related:["What is Option Selling?","Strike Price"] },

  "what-selling":{ title:"What is Option Selling?", level:"Intermediate", mins:"7 min",
    objectives:["Define option selling","Understand premium collection","Grasp the risk profile"],
    explanation:"Option selling means writing options to collect premium and taking on the obligation. Sellers profit when options lose value, mainly through time decay, but they accept larger or undefined risk.",
    concepts:[{h:"Collect premium",p:"The seller is paid upfront and keeps it if the option expires worthless."},{h:"Risk profile",p:"Reward is limited to premium; risk can be large unless the position is a defined-risk spread."}],
    examples:["Selling an OTM Put collects premium if price stays above the strike.","Selling a spread caps the risk at the spread width."],
    ai:"Selling flips the usual trade: high probability of small gains, with the discipline to manage rare large risks. Risk control is everything.",
    formula:"Max profit (naked) = Premium received", mistakes:["Selling naked without understanding risk","Oversizing"],
    best:["Prefer defined-risk while learning","Respect tail risk"],
    quiz:[q("Option sellers mainly profit from...",["Big moves","Time decay","Dividends","Stock splits"],1),q("A seller's reward is...",["Unlimited","Limited to premium","Always large","Guaranteed"],1),q("Defined-risk selling uses...",["Naked options","Spreads","No options","Only futures"],1)],
    takeaways:["Sell to collect premium","Limited reward, manage large risk"],
    related:["Why Sellers Collect Premium","Risk Management"] },
  "why-premium":{ title:"Why Sellers Collect Premium", level:"Intermediate", mins:"6 min",
    objectives:["Understand why premium exists","Link it to probability and time","See the seller's edge and cost"],
    explanation:"Sellers are paid premium for taking on risk and obligation. Most options expire worthless, so sellers have a high probability of small gains, balanced against occasional large losses.",
    concepts:[{h:"Paid for risk",p:"Premium compensates the seller for the chance of a loss."},{h:"Probability edge",p:"Many options expire worthless, giving sellers a statistical tailwind, not a guarantee."}],
    examples:["A far OTM option rarely finishes in-the-money, so sellers often keep the premium.","But a rare large move can cause a loss far bigger than the premium."],
    ai:"The seller's edge is probability and time decay; the cost is tail risk. Good sellers size positions so the rare large loss is survivable.",
    formula:"", mistakes:["Believing premium is free money","Ignoring tail risk"],
    best:["Respect the rare big move","Size for survival"],
    quiz:[q("Sellers are paid premium for...",["Nothing","Taking on risk and obligation","Buying stock","Holding cash"],1),q("Most options at expiry...",["Finish in the money","Expire worthless","Get exercised","Roll automatically"],1),q("The seller's main cost is...",["Brokerage only","Tail risk","Dividends","Nothing"],1)],
    takeaways:["Premium pays for risk","Edge is probability; cost is tail risk"],
    related:["Probability in Option Selling","What is Option Selling?"] },
  "probability":{ title:"Probability in Option Selling", level:"Intermediate", mins:"7 min",
    objectives:["Understand probability of profit","Link Delta to probability","Balance probability and reward"],
    explanation:"Option selling is a probability game. The further out-of-the-money a strike, the higher the chance it expires worthless, but the smaller the premium collected.",
    concepts:[{h:"Delta as probability",p:"An option's Delta roughly approximates its chance of finishing in-the-money."},{h:"Trade-off",p:"Higher probability of profit means lower premium, and vice versa."}],
    examples:["A 0.15 Delta option has roughly a 15% chance of finishing in-the-money.","Selling it gives a high probability of keeping the premium, but the premium is small."],
    ai:"Sellers balance probability against reward. Very high probability trades collect little and can still lose big if unmanaged.",
    formula:"Approx probability ITM = option Delta", mistakes:["Chasing only high probability","Ignoring the size of the rare loss"],
    best:["Balance probability and premium","Always plan for the losing case"],
    quiz:[q("Delta roughly approximates...",["Time decay","Probability of finishing ITM","Volatility","Volume"],1),q("Higher probability of profit usually means...",["More premium","Less premium","No risk","Guaranteed win"],1),q("A 0.10 Delta option finishes ITM about...",["90% of the time","10% of the time","Never","Always"],1)],
    takeaways:["Selling is a probability game","Delta approximates probability"],
    related:["Delta","Why Sellers Collect Premium"] },
  "theta":{ title:"Theta Decay", level:"Intermediate", mins:"6 min",
    objectives:["Define Theta","Understand the decay curve","See why it helps sellers"],
    explanation:"Theta measures how much an option loses in value each day from time passing. It is the seller's main engine, and it accelerates as expiry approaches.",
    concepts:[{h:"Daily decay",p:"Theta is negative for buyers and positive for sellers."},{h:"Acceleration",p:"Theta is small far from expiry and steep in the final days."}],
    examples:["A weekly at-the-money option loses value quickly each afternoon near expiry.","Far-dated options decay slowly at first."],
    ai:"Sellers harvest Theta. The challenge is that high Theta near expiry comes with high Gamma risk, so the reward and danger rise together.",
    formula:"Theta = daily change in option value from time", mistakes:["Expecting linear decay","Ignoring rising Gamma with Theta"],
    best:["Understand the curve","Balance Theta against Gamma"],
    quiz:[q("Theta measures...",["Volatility","Daily time decay","Direction","Liquidity"],1),q("Theta is positive for...",["Buyers","Sellers","Nobody","Brokers"],1),q("Theta accelerates...",["Far from expiry","Near expiry","Never","At open"],1)],
    takeaways:["Theta = daily time decay","Positive for sellers, steep near expiry"],
    related:["Time Value","Gamma"] },
  "iv-basics":{ title:"IV Basics", level:"Intermediate", mins:"6 min",
    objectives:["Define implied volatility","Understand IV Rank","Link IV to premium"],
    explanation:"Implied Volatility (IV) is the market's expectation of future movement, baked into option prices. Higher IV means richer premiums; lower IV means cheaper options.",
    concepts:[{h:"IV and premium",p:"When IV rises, premiums rise even if price does not move."},{h:"IV Rank",p:"IV Rank shows where current IV sits in its yearly range."}],
    examples:["Before results, a stock's IV often rises, inflating premiums.","After the event, IV crush can collapse premiums."],
    ai:"Sellers prefer selling when IV is relatively high, so they collect rich premium and can benefit from IV falling back.",
    formula:"", mistakes:["Selling when IV is very low","Ignoring IV Rank"],
    best:["Sell richer premium in high IV","Track IV Rank and VIX"],
    quiz:[q("IV reflects...",["Past returns","Expected future movement","Dividends","Volume"],1),q("Higher IV makes premiums...",["Cheaper","Richer","Zero","Negative"],1),q("IV Rank shows IV versus its...",["Daily average","Yearly range","Strike","Expiry"],1)],
    takeaways:["IV = expected movement","High IV = richer premium"],
    related:["Vega","Volatility Trading"] },
  "delta":{ title:"Delta", level:"Intermediate", mins:"5 min",
    objectives:["Define Delta","Use Delta as probability","Understand position Delta"],
    explanation:"Delta measures how much an option's price changes for a 1-point move in the underlying. It also roughly approximates the probability of finishing in-the-money.",
    concepts:[{h:"Sensitivity",p:"An ATM option has Delta near 0.5; deep ITM near 1."},{h:"As probability",p:"Delta approximates the chance the option finishes in-the-money."}],
    examples:["A 0.30 Delta call gains about 0.30 for a 1-point rise.","A short put with 0.20 Delta has roughly a 20% chance of finishing ITM."],
    ai:"Sellers use Delta to judge risk and probability at once. Lower Delta strikes are safer but pay less.",
    formula:"Delta = change in option price / change in underlying", mistakes:["Ignoring how Delta drifts","Forgetting position Delta across legs"],
    best:["Use Delta for probability","Track net position Delta"],
    quiz:[q("ATM Delta is around...",["0","0.5","1","2"],1),q("Delta also approximates...",["Time decay","Probability ITM","IV","Volume"],1),q("A higher Delta short option is...",["Safer","Riskier","Free","Guaranteed"],1)],
    takeaways:["Delta = price sensitivity","Also approximates probability"],
    related:["Gamma","Probability in Option Selling"] },
  "gamma":{ title:"Gamma", level:"Intermediate", mins:"5 min",
    objectives:["Define Gamma","Understand Gamma near expiry","See seller Gamma risk"],
    explanation:"Gamma measures how fast Delta changes. It is highest for at-the-money options near expiry, which makes positions move quickly and unpredictably.",
    concepts:[{h:"Speed of Delta",p:"High Gamma means Delta shifts fast with small price moves."},{h:"Near expiry",p:"Gamma peaks at-the-money close to expiry, raising risk."}],
    examples:["On expiry day, a near-strike short option can swing from safe to deep ITM fast.","Far-dated options have low Gamma and move smoothly."],
    ai:"Gamma is the seller's expiry-day danger. The same conditions that give high Theta also bring high Gamma risk.",
    formula:"Gamma = change in Delta / change in underlying", mistakes:["Holding near-strike shorts into expiry casually","Underestimating Gamma"],
    best:["Reduce near-strike exposure into expiry","Respect Gamma"],
    quiz:[q("Gamma measures...",["Time decay","How fast Delta changes","IV","Volume"],1),q("Gamma is highest...",["Far OTM","ATM near expiry","After expiry","On holidays"],1),q("High Gamma means risk is...",["Lower","Higher and faster","Zero","Fixed"],1)],
    takeaways:["Gamma = speed of Delta","Highest ATM near expiry"],
    related:["Delta","Theta Decay"] },
  "vega":{ title:"Vega", level:"Intermediate", mins:"5 min",
    objectives:["Define Vega","Link Vega to IV","Understand seller Vega risk"],
    explanation:"Vega measures how much an option's price changes for a 1% change in implied volatility. Sellers are usually short Vega, so rising IV works against them.",
    concepts:[{h:"IV sensitivity",p:"Higher Vega means more sensitivity to IV changes."},{h:"Seller exposure",p:"Short options have negative Vega; an IV spike hurts them."}],
    examples:["An IV spike before an event raises premiums and short-position losses.","Longer-dated options have more Vega."],
    ai:"Sellers respect Vega because a calm market can turn volatile, and rising IV inflates the options they are short.",
    formula:"Vega = change in option price / 1% change in IV", mistakes:["Ignoring Vega around events","Selling long-dated without Vega awareness"],
    best:["Watch IV before selling","Mind Vega on longer expiries"],
    quiz:[q("Vega measures sensitivity to...",["Price","IV","Time","Volume"],1),q("Short options usually have Vega that is...",["Positive","Negative","Zero","Undefined"],1),q("An IV spike hurts...",["Buyers","Sellers who are short Vega","Nobody","Only futures"],1)],
    takeaways:["Vega = IV sensitivity","Sellers are usually short Vega"],
    related:["IV Basics","Volatility Trading"] },
  "margin-basics":{ title:"Margin Basics", level:"Intermediate", mins:"6 min",
    objectives:["Understand margin for sellers","Know span and exposure margin","See why margin can rise"],
    explanation:"Margin is the capital blocked to cover potential losses on short options. It is made of span and exposure margin and can rise when volatility increases.",
    concepts:[{h:"Span and exposure",p:"Span covers worst-case risk; exposure is an extra buffer."},{h:"Margin changes",p:"Margin can rise with volatility or before events, sometimes forcing exits."}],
    examples:["A short straddle needs large margin that grows if VIX spikes.","Defined-risk spreads need far less margin."],
    ai:"Sellers keep a margin buffer so a volatility spike does not force a panic exit at the worst time.",
    formula:"Total margin = Span margin + Exposure margin", mistakes:["Using all margin with no buffer","Ignoring margin rises before events"],
    best:["Keep a margin buffer","Reduce size in high volatility"],
    quiz:[q("Margin for sellers is made of...",["Only span","Span + exposure","Only exposure","Brokerage"],1),q("Margin can rise when...",["VIX falls","Volatility spikes","Markets close","Nothing happens"],1),q("Defined-risk spreads need...",["More margin","Less margin","No margin","Infinite margin"],1)],
    takeaways:["Margin = span + exposure","Rises with volatility"],
    related:["Risk Management","Portfolio Margin"] },
  "risk-mgmt":{ title:"Risk Management", level:"Intermediate", mins:"7 min",
    objectives:["Apply position sizing","Use defined-risk structures","Build a risk checklist"],
    explanation:"Risk management is the most important skill in option selling. It is about sizing positions, defining risk, and protecting capital so rare large losses stay survivable.",
    concepts:[{h:"Sizing",p:"Risk only a small part of capital per idea."},{h:"Defined risk",p:"Spreads cap the loss; naked positions do not."},{h:"Checklist",p:"Check events, margin, and size before every position."}],
    examples:["A seller risking 2% per idea survives a bad expiry easily.","A seller using all margin on one naked straddle can be wiped by one gap."],
    ai:"The best sellers lose small and often, win small and often, and never let one position threaten the account.",
    formula:"", mistakes:["Oversizing","No plan for losses","Averaging into losers"],
    best:["Size small","Prefer defined risk","Follow a checklist"],
    quiz:[q("The most important seller skill is...",["Prediction","Risk management","Speed","Leverage"],1),q("Defined-risk positions...",["Have unlimited loss","Cap the loss","Need no margin","Always profit"],1),q("Good sizing means risking...",["All capital","A small part per idea","Nothing","Borrowed money"],1)],
    takeaways:["Protect capital first","Size small, define risk"],
    related:["Margin Basics","Position Adjustment"] },

  "iron-condor":{ title:"Iron Condor", level:"Advanced", mins:"8 min",
    objectives:["Understand the Iron Condor","Know its payoff and risk","See when it is studied"],
    explanation:"An Iron Condor sells an out-of-the-money Put spread and an out-of-the-money Call spread, profiting if price stays in a range. Risk is defined on both sides.",
    concepts:[{h:"Structure",p:"Sell a Put spread below and a Call spread above the price."},{h:"Profit zone",p:"Maximum profit if price stays between the short strikes at expiry."}],
    examples:["In a calm, range-bound market, the Condor collects premium on both sides.","A breakout beyond a wing reaches the defined maximum loss."],
    ai:"The Iron Condor is a classic range strategy. It has strong positive Theta and defined risk, but it suffers if price trends out of the range.",
    formula:"Max profit = net credit; Max loss = wing width - net credit", mistakes:["Setting wings too tight","Holding through a big event"],
    best:["Use in low-volatility ranges","Define wings to your risk comfort"],
    quiz:[q("An Iron Condor profits when price...",["Trends hard","Stays in a range","Gaps","Crashes"],1),q("Its risk is...",["Unlimited","Defined on both sides","Only on calls","Zero"],1),q("Max profit equals...",["Wing width","Net credit","Strike price","Spot"],1)],
    takeaways:["Range strategy, defined risk","Strong positive Theta"],
    related:["Iron Fly","Short Strangle"] },
  "iron-fly":{ title:"Iron Fly", level:"Advanced", mins:"7 min",
    objectives:["Understand the Iron Butterfly","Compare it to the Condor","Know its narrow profit zone"],
    explanation:"An Iron Fly sells an at-the-money Put and Call (a short straddle) and buys protective wings. It collects high premium but has a narrow profit zone centered on the strike.",
    concepts:[{h:"Structure",p:"Short ATM straddle plus long wings for protection."},{h:"Narrow zone",p:"Maximum profit only if price pins the center strike."}],
    examples:["When very little movement is expected, the Iron Fly collects rich premium.","A move away from the center quickly reduces profit."],
    ai:"The Iron Fly is a high-credit, narrow-target version of the Condor. It needs a strong pin near the strike to reach maximum profit.",
    formula:"Max profit at center strike; Max loss = wing width - net credit", mistakes:["Expecting a pin every time","Underestimating Gamma near expiry"],
    best:["Use when expecting a tight range","Respect Gamma near expiry"],
    quiz:[q("An Iron Fly is built around...",["Far OTM strikes","An ATM short straddle plus wings","Only calls","Futures"],1),q("Its profit zone is...",["Wide","Narrow","Unlimited","None"],1),q("Max profit needs price to...",["Trend","Pin the center strike","Gap","Crash"],1)],
    takeaways:["High credit, narrow target","Needs a pin near the strike"],
    related:["Iron Condor","Short Straddle"] },
  "short-strangle":{ title:"Short Strangle", level:"Advanced", mins:"7 min",
    objectives:["Understand the Short Strangle","Know its undefined risk","See when it is studied"],
    explanation:"A Short Strangle sells an out-of-the-money Call and an out-of-the-money Put, profiting if price stays between the strikes. Risk is undefined beyond the strikes.",
    concepts:[{h:"Structure",p:"Sell an OTM Call and an OTM Put."},{h:"Undefined risk",p:"Losses grow without limit if price moves far beyond a strike."}],
    examples:["In a range with elevated IV, the Strangle collects premium on both sides.","A strong trend beyond a strike causes large losses."],
    ai:"The Short Strangle has strong Theta and a wide profit zone, but undefined risk means strict sizing and discipline are essential.",
    formula:"Max profit = total premium; Loss is undefined beyond strikes", mistakes:["Strikes too close","Holding into a trend"],
    best:["Use wide strikes with high IV","Size strictly for undefined risk"],
    quiz:[q("A Short Strangle profits when price...",["Trends","Stays between strikes","Gaps","Crashes"],1),q("Its risk is...",["Defined","Undefined beyond strikes","Zero","On calls only"],1),q("It works best when IV is...",["Very low","Elevated","Zero","Negative"],1)],
    takeaways:["Range strategy, undefined risk","Strict sizing required"],
    related:["Short Straddle","Iron Condor"] },
  "short-straddle":{ title:"Short Straddle", level:"Advanced", mins:"7 min",
    objectives:["Understand the Short Straddle","Know its high premium and risk","See expiry behaviour"],
    explanation:"A Short Straddle sells an at-the-money Call and Put at the same strike, collecting rich premium. It profits if price stays near the strike, with undefined risk on both sides.",
    concepts:[{h:"Structure",p:"Sell an ATM Call and an ATM Put."},{h:"Risk",p:"Undefined on both sides; needs a pin near the strike."}],
    examples:["When very low movement and falling IV are expected, the Straddle collects high premium.","Any sizable move causes losses."],
    ai:"The Short Straddle is the highest-premium, highest-risk seller study. It demands respect for Gamma and events.",
    formula:"Max profit at the strike; Loss is undefined", mistakes:["Selling before events","No hedge against a gap"],
    best:["Use only with strict risk control","Avoid major events"],
    quiz:[q("A Short Straddle sells...",["Two far OTM options","An ATM Call and Put","Only a Call","Futures"],1),q("Its risk is...",["Defined","Undefined","Zero","On puts only"],1),q("It needs price to...",["Trend","Pin the strike","Gap","Crash"],1)],
    takeaways:["Highest premium and risk","Needs a pin, respect events"],
    related:["Short Strangle","Iron Fly"] },
  "credit-spreads":{ title:"Credit Spreads", level:"Advanced", mins:"7 min",
    objectives:["Understand credit spreads","Know defined risk","Compare bull put and bear call"],
    explanation:"A credit spread sells one option and buys a further option to cap risk, collecting a net credit. Bull Put spreads are bullish; Bear Call spreads are bearish.",
    concepts:[{h:"Defined risk",p:"The long leg caps the maximum loss."},{h:"Directional bias",p:"Bull Put for a bullish view; Bear Call for a bearish view."}],
    examples:["A Bull Put spread profits if price stays above the short put strike.","A Bear Call spread profits if price stays below the short call strike."],
    ai:"Credit spreads are the building blocks of defined-risk selling. They trade some premium for a known maximum loss.",
    formula:"Max loss = strike width - net credit", mistakes:["Going too wide and risking too much","Choosing illiquid strikes"],
    best:["Use for defined-risk directional views","Mind liquidity in both legs"],
    quiz:[q("A credit spread's risk is...",["Unlimited","Defined by the long leg","Zero","On both sides"],1),q("A Bull Put spread is...",["Bearish","Bullish","Neutral only","Random"],1),q("Max loss equals...",["Net credit","Strike width - net credit","Spot","Premium x 2"],1)],
    takeaways:["Defined-risk directional selling","Long leg caps the loss"],
    related:["Iron Condor","Hedging"] },
  "hedging":{ title:"Hedging", level:"Advanced", mins:"7 min",
    objectives:["Understand hedging for sellers","Know common hedge tools","See cost vs protection"],
    explanation:"Hedging reduces the risk of a short option position by adding an offsetting position, such as buying a further option or using futures. It trades some profit for protection.",
    concepts:[{h:"Why hedge",p:"Undefined-risk positions can be capped by adding a long option."},{h:"Cost",p:"Hedges cost premium and reduce maximum profit."}],
    examples:["Buying a far Put hedges a short Put against a crash.","Converting a naked position into a spread caps the loss."],
    ai:"Hedging is about survival. A seller gives up some premium to ensure no single move can cause a catastrophic loss.",
    formula:"", mistakes:["Hedging too late","Over-hedging away all profit"],
    best:["Hedge before trouble, not during","Balance cost and protection"],
    quiz:[q("Hedging a short option...",["Increases risk","Reduces risk for some cost","Is free","Guarantees profit"],1),q("A common hedge is...",["Selling more","Buying a further option","Doing nothing","Adding leverage"],1),q("Hedges generally...",["Raise max profit","Reduce max profit","Have no effect","Remove all risk free"],1)],
    takeaways:["Hedging trades profit for protection","Cap catastrophic risk"],
    related:["Credit Spreads","Position Adjustment"] },
  "greeks-selling":{ title:"Greeks in Selling", level:"Advanced", mins:"7 min",
    objectives:["Combine Greeks for sellers","Read net position Greeks","Balance Theta and Gamma"],
    explanation:"For sellers, the Greeks work together: positive Theta is the reward, while negative Gamma and negative Vega are the risks. Reading net position Greeks is essential.",
    concepts:[{h:"Reward and risk",p:"Theta helps; Gamma and Vega can hurt."},{h:"Net Greeks",p:"Across multiple legs, the net position Greeks define the real exposure."}],
    examples:["A short straddle has high positive Theta but strong negative Gamma and Vega.","An Iron Condor softens Gamma and Vega risk with its wings."],
    ai:"Sellers manage a balance: harvest Theta while keeping Gamma and Vega risk within limits they can survive.",
    formula:"", mistakes:["Watching one Greek in isolation","Ignoring net position Greeks"],
    best:["Read net Greeks across legs","Balance Theta against Gamma and Vega"],
    quiz:[q("For sellers, Theta is usually...",["A risk","A reward","Irrelevant","Negative"],1),q("Sellers are usually short...",["Theta","Gamma and Vega","Cash","Nothing"],1),q("Net Greeks should be read...",["Per leg only","Across all legs","Never","At expiry only"],1)],
    takeaways:["Theta rewards, Gamma and Vega risk","Read net position Greeks"],
    related:["Gamma","Vega"] },
  "vol-trading":{ title:"Volatility Trading", level:"Advanced", mins:"7 min",
    objectives:["Understand trading volatility","Use IV Rank","Plan around IV crush"],
    explanation:"Volatility trading focuses on implied volatility rather than direction. Sellers often sell when IV is high, expecting it to fall, and stay cautious when IV is low.",
    concepts:[{h:"Sell high IV",p:"Rich premium and potential IV crush favour sellers."},{h:"IV crush",p:"After events, IV often falls sharply, helping short positions."}],
    examples:["Selling premium before results can benefit from post-event IV crush, if the move is contained.","Selling in very low IV collects little and risks an IV spike."],
    ai:"Volatility traders study IV Rank and VIX to judge whether premium is rich. The view is on volatility, not just price.",
    formula:"", mistakes:["Selling in very low IV","Ignoring the event move that comes with IV crush"],
    best:["Prefer high IV Rank to sell","Plan for the event move, not just the crush"],
    quiz:[q("Volatility trading focuses on...",["Only direction","Implied volatility","Dividends","Volume only"],1),q("Sellers prefer to sell when IV is...",["Low","High","Zero","Negative"],1),q("IV crush usually happens...",["Before events","After events","Never","At open"],1)],
    takeaways:["Trade IV, not just price","Sell high IV, respect the event move"],
    related:["IV Basics","Vega"] },
  "position-adjust":{ title:"Position Adjustment", level:"Advanced", mins:"7 min",
    objectives:["Understand adjustments","Know common adjustment tools","Decide when to adjust"],
    explanation:"Position adjustment means changing a position as the market moves, to manage risk or improve the outlook. Common adjustments include adding hedges, rolling, or reducing size.",
    concepts:[{h:"Why adjust",p:"To reduce risk when a position moves against you, within a plan."},{h:"Tools",p:"Hedging, rolling, and reducing size are common adjustments."}],
    examples:["A tested short strike can be hedged with a long option.","A position can be reduced to cut risk after a move."],
    ai:"Good adjustments follow a plan made in advance, not panic. The aim is to keep risk survivable, not to avoid every loss.",
    formula:"", mistakes:["Adjusting in panic","Adding risk to a losing position"],
    best:["Plan adjustments in advance","Adjust to reduce risk, not chase"],
    quiz:[q("Position adjustment aims to...",["Avoid all losses","Manage risk within a plan","Add leverage","Guarantee profit"],1),q("A common adjustment is...",["Doubling down blindly","Hedging or rolling","Ignoring the position","Removing margin"],1),q("Adjustments should be...",["Improvised in panic","Planned in advance","Random","Avoided always"],1)],
    takeaways:["Adjust by plan, not panic","Keep risk survivable"],
    related:["Rolling Positions","Hedging"] },
  "rolling":{ title:"Rolling Positions", level:"Advanced", mins:"6 min",
    objectives:["Understand rolling","Know roll out and roll up or down","See the trade-offs"],
    explanation:"Rolling means closing an existing option position and opening a similar one at a different strike or expiry, often to manage a tested position or extend time.",
    concepts:[{h:"Roll out",p:"Move to a later expiry for more time."},{h:"Roll up or down",p:"Move the strike to adjust risk and direction."}],
    examples:["A tested short Put can be rolled down and out to a safer strike and later expiry.","Rolling can collect more credit but extends the risk window."],
    ai:"Rolling buys time and adjusts risk, but it is not a magic fix. It should follow a plan and respect total risk.",
    formula:"", mistakes:["Rolling losers endlessly","Ignoring added risk from more time"],
    best:["Roll with a plan and a limit","Respect total accumulated risk"],
    quiz:[q("Rolling out moves to...",["A nearer expiry","A later expiry","No expiry","Cash"],1),q("Rolling can be used to...",["Guarantee profit","Manage a tested position","Remove all risk","Avoid taxes"],1),q("A danger of rolling is...",["Less time","Rolling losers endlessly","No credit ever","Nothing"],1)],
    takeaways:["Rolling adjusts strike or expiry","Use a plan, respect total risk"],
    related:["Position Adjustment","Expiry Strategies"] },
  "portfolio-margin":{ title:"Portfolio Margin", level:"Advanced", mins:"6 min",
    objectives:["Understand portfolio-level margin","See netting across positions","Know the risks"],
    explanation:"Portfolio margin looks at the total risk of all positions together, sometimes lowering margin when positions offset each other. It rewards balanced books but magnifies concentrated risk.",
    concepts:[{h:"Netting",p:"Offsetting positions can reduce total margin."},{h:"Concentration",p:"A one-sided book can see margin spike together in a stress event."}],
    examples:["A balanced book of spreads may need less margin than the sum of parts.","A concentrated one-sided book can face a large combined margin call."],
    ai:"Portfolio thinking helps sellers manage total exposure, but it also means a single market shock can hit many positions at once.",
    formula:"", mistakes:["Assuming low margin means low risk","Concentrating on one side"],
    best:["Keep the book balanced","Watch total portfolio risk, not just per trade"],
    quiz:[q("Portfolio margin looks at...",["One trade only","Total risk of all positions","Brokerage","Dividends"],1),q("Offsetting positions can...",["Raise margin always","Lower total margin","Remove risk","Do nothing"],1),q("A concentrated book risks...",["Nothing","A large combined margin call","Lower risk","Free margin"],1)],
    takeaways:["Margin viewed across the whole book","Balance lowers risk; concentration raises it"],
    related:["Margin Basics","Risk Management"] },
  "event-trading":{ title:"Event Trading", level:"Advanced", mins:"7 min",
    objectives:["Understand event risk and IV","Plan around events","Know IV crush trade-offs"],
    explanation:"Event trading focuses on scheduled events like results, RBI policy, the budget, and Fed decisions. IV usually rises before events and crushes after, while the move itself can be large.",
    concepts:[{h:"IV ramp and crush",p:"IV climbs into the event and falls sharply after."},{h:"The move",p:"The event can cause a large price move that hurts unhedged sellers."}],
    examples:["Selling before results can benefit from IV crush if the move is contained.","A surprise result can gap the stock far beyond the expected move."],
    ai:"Event trading is a balance: IV crush helps sellers, but the event move can hurt. Many sellers reduce size or use defined risk around events.",
    formula:"", mistakes:["Selling naked into events","Ignoring the size of the possible move"],
    best:["Use defined risk around events","Reduce size into major events"],
    quiz:[q("Before events, IV usually...",["Falls","Rises","Vanishes","Stays flat"],1),q("After events, IV often...",["Rises more","Crushes lower","Stays high","Goes negative"],1),q("The danger in event trading is...",["IV crush","The large event move","Low volume","Nothing"],1)],
    takeaways:["IV ramps then crushes around events","The event move is the real risk"],
    related:["Volatility Trading","Expiry Strategies"] },
  "expiry-strategies":{ title:"Expiry Strategies", level:"Advanced", mins:"7 min",
    objectives:["Understand expiry-day dynamics","Balance Theta and Gamma","Plan expiry behaviour"],
    explanation:"Near expiry, Theta decay is fastest and Gamma risk is highest. Expiry strategies study how to harvest the final decay while controlling the sharp risk of last-minute moves.",
    concepts:[{h:"Fast decay",p:"The final hours see rapid time-value erosion."},{h:"High Gamma",p:"Small moves cause large Delta swings near expiry."}],
    examples:["A near-strike short option can flip from worthless to costly in the final hour.","Far-from-price strikes decay calmly into expiry."],
    ai:"Expiry strategies are about respecting that the biggest reward and the biggest risk arrive together on the final day.",
    formula:"", mistakes:["Holding near-strike shorts to the close casually","Ignoring expiry-day Gamma"],
    best:["Size down on expiry day","Keep clear rules for the final hour"],
    quiz:[q("Near expiry, Theta decay is...",["Slow","Fastest","Zero","Negative"],1),q("Near expiry, Gamma risk is...",["Lowest","Highest","Zero","Fixed"],1),q("Expiry day brings...",["Only reward","Reward and risk together","No change","Only risk-free gains"],1)],
    takeaways:["Fast Theta and high Gamma together","Plan and size down on expiry day"],
    related:["Rolling Positions","Event Trading"] }
};
